# SILAN SUV Platform Support
snd-soc-suv-pcm-objs := suv_pcm.o
snd-soc-suv-i2s-dlna-objs := dlna_i2s.o
snd-soc-suv-spdif-objs := suv_spdif.o
snd-soc-dlna-spdif-in-objs := dlna_spdif_in.o
snd-soc-suv-objs := suv_dwc.o
snd-soc-silan_codec-objs := silan_codec.o

obj-$(CONFIG_SND_SUV_SOC_PCM) += snd-soc-suv-pcm.o
obj-$(CONFIG_SND_SUV_SOC_I2S_DLNA) += snd-soc-suv-i2s-dlna.o
obj-$(CONFIG_SND_SOC_SILAN_CODEC) += snd-soc-silan_codec.o
obj-$(CONFIG_SND_SUV_SOC_SPDIF_OUT) += snd-soc-suv-spdif.o
obj-$(CONFIG_SND_SUV_SOC_SPDIF_IN) += snd-soc-dlna-spdif-in.o
obj-$(CONFIG_SND_SOC_SILAN) += snd-soc-suv.o
