#ifndef __SUV_I2S_HDMI_H
#define __SUV_I2S_HDMI_H

#define IIS_FIFO_DEPTH          64  //
#define IIS_DMABREQ_SIZE        4   // 

#define IIS_CTRL							(0x00)
	#define RX_UNITE_EN				(1<<31)
	#define RX_UNITE_CHNLMASK		(0xf<<27)
	#define RX_UNITE_CHNLSHIFT		(27)
	#define TX_UNITE_EN				(1<<26)
	#define TX_UNITE_CHNLMASK		(0xf<<22)
	#define TX_UNITE_CHNLSHIFT		(22)
	#define TXFLUSH					(1<<20)
	#define ITXEN					(1<<16)
	#define RXFLUSH					(1<<12)
	#define IRXEN					(1<<8)
	#define IIS_EN					(1<<0)

#define CLK_CTRL							(0x04)
	#define SCLK_GLITCHSEL_SHIFT	(29)
	#define SDI_GLITCHSEL_SHIFT		(26)
		#define GLITCH2			(0x0)
		#define GLITCH3			(0x1)
		#define GLITCH4			(0x2)
		#define GLITCH5			(0x3)
		#define GLITCH6			(0x4)
		#define GLITCH_NO		(0x6)
		#define GLITCH_EXT		(0x7)
	#define MODE_EN					(1<<24)
	#define SCLKGATE_SHIFT			(16)
		#define GATENO			(0x0)
		#define GATE12			(0x1)
		#define GATE16			(0x2)
		#define GATE20			(0x3)
		#define GATE24			(0x4)
	#define WSS_SHIFT				(8)
		#define WSS16			(0x0)
		#define WSS24			(0x1)
		#define WSS32			(0x2)
	#define CLK_INV					(1<<5)
	#define PCM_MODE				(1<<4)
	#define CLKEN					(1<<0)

#define CAPTURE								(0x08)

#define ISRG								(0x0c)
	#define	TXCONFIGERRINTR			(1<<30)
	#define	RXCONFIGERRINTR			(1<<27)
	#define	CONFIGERRMASK			(1<<26)
	#define TXFO_X(x)				(1<<5 + 8 * (x))
	#define TXFE_X(x)				(1<<4 + 8 * (x))
	#define RXFO_X(x)				(1<<1 + 8 * (x))
	#define RXDA_X(x)				(1<<0 + 8 * (x))

#define RFR_X(x)							(0x10 + 0x20 * (x))
#define TFR_X(x)							(0x14 + 0x20 * (x))

#define RCR_X(x)							(0x18 + 0x20 * (x))
#define TCR_X(x)							(0x1c + 0x20 * (x))
	#define RTFF					(1<<31)
	#define RTXFTHD_MASK			(0x1f<<24)
	#define RTXFTHD_SHIFT			(24)
	#define RTXMOTOSEL				(1<<21)
	#define RTXJUST_LOW				(1<<20)
	#define RTXJUST_HIGH			(0<<20)
	#define RTXMODE_MASK			(0x3<<16)
	#define RTXMODE_LEFT			(0<<16)
	#define RTXMODE_RITHT			(1<<16)
	#define RTXMODE_IIS				(2<<16)
	#define RTXMODE_DSP				(3<<16)
	#define RTWLEN_MASK				(0x7<<8)
	#define RTWLEN_SHIFT			(8)
	#define WLEN_8BIT				(0x1)
	#define WLEN_12BIT				(0x2)
	#define WLEN_16BIT				(0x3)
	#define WLEN_20BIT				(0x4)
	#define WLEN_24BIT				(0x5)
	#define WLEN_32BIT				(0x6)
	#define RTXDMAEN				(1<<4)
	#define RTXEN					(1<<0)

#define ISR_X(x)							(0x20 + 0x20 * (x))
	#define TXFO					(1<<5)
	#define TXFE					(1<<4)
	#define RXFO					(1<<1)
	#define RXDA					(1<<0)
#define IMR_X(x)							(0x24 + 0x20 * (x))
	#define TXFOM					(1<<5)
	#define TXFEM					(1<<4)
	#define RXFOM					(1<<1)
	#define RXDAM					(1<<0)

#define TXFIFO_X(x)							(0x28 + 0x20 * (x))
#define RXFIFO_X(x)							(0x2c + 0x20 * (x))

#define KER									(0x90)
#define SRESET								(0x94)
	#define SRST_ALL				(0x72558841)

#endif
