#ifndef __SL_RESET_H
#define __SL_RESET_H

typedef enum {
	SILAN_SR_START = 0,
	SILAN_SR_SPDIF = SILAN_SR_START,
	SILAN_SR_IIS_DAC,
	SILAN_SR_IIS_ADC,
	SILAN_SR_CODEC,
	SILAN_SR_HS_UART = 5,
	SILAN_SR_LS_UART,
	SILAN_SR_USB_PHY,
	SILAN_SR_USB_AHB,

	SILAN_SR_SDMMC = 10,
	SILAN_SR_SDIO  = 12,
	SILAN_SR_GMAC  = 15,
	SILAN_SR_I2C,
	SILAN_SR_USBFS_PHY,
	SILAN_SR_USBFS_AHB,
	SILAN_SR_MCCLK,
	SILAN_SR_END,
}RSTMOD;

int silan_module_rst(RSTMOD module);

#endif
