/*
 * Data type definition of prom memory allocator for DLNA
 *
 * xuhang@silan.com.cn
 */
#ifndef _SILAN_MEMORY_H
#define _SILAN_MEMORY_H

/* Device ID */

typedef enum {
	SILAN_DEV_START = 0,
	/* DUMMY can be used if the user is not a specific device */
	SILAN_DEV_DUMMY = SILAN_DEV_START,

	SILAN_DEV_USBHOST,
	SILAN_DEV_USBOTG,
	SILAN_DEV_GMAC,
	SILAN_DEV_DMAC0,
	SILAN_DEV_DMAC1,
	SILAN_DEV_SPDIF,
	SILAN_DEV_I2ST4,
	SILAN_DEV_I2SMIC,
	SILAN_DEV_I2SHDMI,
	SILAN_DEV_DSP0,
	SILAN_DEV_TIMER,
	SILAN_DEV_SPI,
	SILAN_DEV_UART1,	/* LSP */
	SILAN_DEV_UART2,	/* LSP */
	SILAN_DEV_HUART3,	/* PXB */
	SILAN_DEV_HUART4,	/* PXB */
	SILAN_DEV_HUART5,	/* PXB */
	SILAN_DEV_HUART6,	/* PXB */
	SILAN_DEV_I2C1,
	SILAN_DEV_I2C2,
	SILAN_DEV_I2C3,
	SILAN_DEV_I2C4,
	SILAN_DEV_I2C5,
	SILAN_DEV_PMU,
	SILAN_DEV_WATCHDOG,
	SILAN_DEV_GPIO1,
	SILAN_DEV_GPIO2,
	SILAN_DEV_GPIO3,
	SILAN_DEV_GPIO4,
	SILAN_DEV_GPIO5,
	SILAN_DEV_SSP1,
	SILAN_DEV_SSP2,
	SILAN_DEV_OTP,
	SILAN_DEV_SD,
	SILAN_DEV_EMMC,
	SILAN_DEV_SDIO,
	SILAN_DEV_SCI,
	SILAN_DEV_PWM,
	SILAN_DEV_RTC,
	SILAN_DEV_APWM,
	SILAN_DEV_UNICOM,

	SILAN_DEV_END, 
} SILAN_DEV_ID;

u32 prom_phy_mem_malloc(u32 size, int id);

#endif /* _SILAN_MEMORY_H */
