#ifndef __SL_PADMUX_H
#define __SL_PADMUX_H

typedef enum {
    SILAN_PADMUX_START = 0,
    
    SILAN_PADMUX_UART1 = SILAN_PADMUX_START,
    SILAN_PADMUX_UART2,
    SILAN_PADMUX_IISDAC_MCLK,
    SILAN_PADMUX_IISADC_MCLK,
    SILAN_PADMUX_SPI = 5,
    SILAN_PADMUX_SPI_EX,
    SILAN_PADMUX_SDMMC,
    SILAN_PADMUX_SDIO,
    SILAN_PADMUX_SDMMCDET,
    SILAN_PADMUX_SDIODET,
    SILAN_PADMUX_IISADC = 12,
    SILAN_PADMUX_IISADC_FD,
    SILAN_PADMUX_IISADC_HD,
    SILAN_PADMUX_IISDAC,
    SILAN_PADMUX_IISDAC_FD0,
    SILAN_PADMUX_IISDAC_FD1,
    SILAN_PADMUX_IISDAC_FD2,
    SILAN_PADMUX_IISDAC_HD0,
    SILAN_PADMUX_IISDAC_HD1,
    SILAN_PADMUX_IISDAC_HD2,
    SILAN_PADMUX_SPDIF,
    SILAN_PADMUX_USB_TEST,
    SILAN_PADMUX_SF_QUAD,
    SILAN_PADMUX_SP_SPI,
    SILAN_PADMUX_GMAC,
    SILAN_PADMUX_I2C1,
    SILAN_PADMUX_SPI_EXT2,

    SILAN_PADMUX_END
}PADMUX;

typedef enum {
    PAD_OFF,
    PAD_ON,
}PAD_ON_OFF;

int silan_padmux_ctrl(PADMUX pad, PAD_ON_OFF flag);

#endif
