EXTRA_CFLAGS += -Dlinux -DDWC_HS_ELECT_TST  -DDWC_LINUX -DPLATFORM_INTERFACE -DBRITE_USB_PHY 

obj-$(CONFIG_USB_DWC_HCD) += silandwcotg_new.o

silandwcotg_new-objs := dwc_otg_driver.o  dwc_otg_attr.o dwc_otg_cil.o dwc_otg_cil_intr.o dwc_otg_pcd_linux.o dwc_otg_pcd.o dwc_otg_pcd_intr.o dwc_otg_hcd.o dwc_otg_hcd_linux.o dwc_otg_hcd_intr.o dwc_otg_hcd_queue.o dwc_otg_hcd_ddma.o dwc_otg_cfi.o  dwc_cc.o  dwc_crypto.o dwc_notifier.o dwc_common_linux.o dwc_mem.o


