//------------------------------------------------------------------------------
// File: RegDefine.h
//
// Copyright (c) 2006~2010, Silan Inc.  All rights reserved.
//------------------------------------------------------------------------------

#ifndef REGDEFINE_H_INCLUDED
#define REGDEFINE_H_INCLUDED

#include"viu.h"
extern viu_dev * g_dev_info;
//------------------------------------------------------------------------------
// REGISTER BASE
//------------------------------------------------------------------------------
#define REG_BASE                       (unsigned int)(g_dev_info->viu_base)

// Configure Register address define
#define VI0_PORT_CFG                   ( REG_BASE + 0x0000)
#define VI2_PORT_CFG                   ( REG_BASE + 0x2000)
#define VI4_PORT_CFG                   ( REG_BASE + 0x4000)
#define VI6_PORT_CFG                   ( REG_BASE + 0x6000)
                                       
#define VI0_CH_CFG                     ( REG_BASE + 0x0004)
#define VI1_CH_CFG                     ( REG_BASE + 0x1004)
#define VI2_CH_CFG                     ( REG_BASE + 0x2004)
#define VI3_CH_CFG                     ( REG_BASE + 0x3004)
#define VI4_CH_CFG                     ( REG_BASE + 0x4004)
#define VI5_CH_CFG                     ( REG_BASE + 0x5004)
#define VI6_CH_CFG                     ( REG_BASE + 0x6004)
#define VI7_CH_CFG                     ( REG_BASE + 0x7004)

#define STORE_MODE_PLANAR  (0x0<<8)
#define STORE_MODE_SEMIPLANAR  (0x1<<8)
#define STORE_MODE_PACKAGE  (0x2<<8)
#define STORE_MODE_RAW  (0x3<<8)

#define MIRROR_MODE  (0x1<<30)
#define FLIP_MODE  (0x1<<29)

#define SCALE_MODE_NONE  (0x0<<10)
#define SCALE_MODE_1_2  (0x1<<10)
#define SCALE_MODE_1_4  (0x2<<10)
#define SCALE_MODE_1_8  (0x3<<10)


#define CAP_SEL_ODD  (0x0<<6)
#define CAP_SEL_EVEN  (0x1<<6)
#define CAP_SEL_BOTH  (0x2<<6)

#define INPUT_ORDER_CBYCRY (0x0<<4)
#define INPUT_ORDER_CRYCBY (0x1<<4)
#define INPUT_ORDER_YCBYCR (0x2<<4)
#define INPUT_ORDER_YCRYCB (0x3<<4)

#define STORE_MODE_FIELD (0x0<<2)
#define STORE_MODE_FRAME (0x1<<2)

#define VI0_CH_CTRL                    ( REG_BASE + 0x0008)
#define VI1_CH_CTRL                    ( REG_BASE + 0x1008)
#define VI2_CH_CTRL                    ( REG_BASE + 0x2008)
#define VI3_CH_CTRL                    ( REG_BASE + 0x3008)
#define VI4_CH_CTRL                    ( REG_BASE + 0x4008)
#define VI5_CH_CTRL                    ( REG_BASE + 0x5008)
#define VI6_CH_CTRL                    ( REG_BASE + 0x6008)
#define VI7_CH_CTRL                    ( REG_BASE + 0x7008)
                                       
#define MASK_0  (0x1<<4)
#define MASK_1  (0x1<<5)
#define MASK_2  (0x1<<6)
#define MASK_3  (0x1<<7)

#define VI0_REG_NEWER                  ( REG_BASE + 0x000C)
#define VI1_REG_NEWER                  ( REG_BASE + 0x100C)
#define VI2_REG_NEWER                  ( REG_BASE + 0x200C)
#define VI3_REG_NEWER                  ( REG_BASE + 0x300C)
#define VI4_REG_NEWER                  ( REG_BASE + 0x400C)
#define VI5_REG_NEWER                  ( REG_BASE + 0x500C)
#define VI6_REG_NEWER                  ( REG_BASE + 0x600C)
#define VI7_REG_NEWER                  ( REG_BASE + 0x700C)
                                       
#define VI0_CAP_START                  ( REG_BASE + 0x0010)
#define VI1_CAP_START                  ( REG_BASE + 0x1010)
#define VI2_CAP_START                  ( REG_BASE + 0x2010)
#define VI3_CAP_START                  ( REG_BASE + 0x3010)
#define VI4_CAP_START                  ( REG_BASE + 0x4010)
#define VI5_CAP_START                  ( REG_BASE + 0x5010)
#define VI6_CAP_START                  ( REG_BASE + 0x6010)
#define VI7_CAP_START                  ( REG_BASE + 0x7010)

#define VI0_CAP_SIZE                   ( REG_BASE + 0x0014)
#define VI1_CAP_SIZE                   ( REG_BASE + 0x1014)
#define VI2_CAP_SIZE                   ( REG_BASE + 0x2014)
#define VI3_CAP_SIZE                   ( REG_BASE + 0x3014)
#define VI4_CAP_SIZE                   ( REG_BASE + 0x4014)
#define VI5_CAP_SIZE                   ( REG_BASE + 0x5014)
#define VI6_CAP_SIZE                   ( REG_BASE + 0x6014)
#define VI7_CAP_SIZE                   ( REG_BASE + 0x7014)
                                       
#define VI0_Y_STORESIZE                ( REG_BASE + 0x0018)
#define VI1_Y_STORESIZE                ( REG_BASE + 0x1018)
#define VI2_Y_STORESIZE                ( REG_BASE + 0x2018)
#define VI3_Y_STORESIZE                ( REG_BASE + 0x3018)
#define VI4_Y_STORESIZE                ( REG_BASE + 0x4018)
#define VI5_Y_STORESIZE                ( REG_BASE + 0x5018)
#define VI6_Y_STORESIZE                ( REG_BASE + 0x6018)
#define VI7_Y_STORESIZE                ( REG_BASE + 0x7018)
                                       
#define VI0_U_STORESIZE                ( REG_BASE + 0x001C)
#define VI1_U_STORESIZE                ( REG_BASE + 0x101C)
#define VI2_U_STORESIZE                ( REG_BASE + 0x201C)
#define VI3_U_STORESIZE                ( REG_BASE + 0x301C)
#define VI4_U_STORESIZE                ( REG_BASE + 0x401C)
#define VI5_U_STORESIZE                ( REG_BASE + 0x501C)
#define VI6_U_STORESIZE                ( REG_BASE + 0x601C)
#define VI7_U_STORESIZE                ( REG_BASE + 0x701C)
                                       
#define VI0_V_STORESIZE                ( REG_BASE + 0x0020)
#define VI1_V_STORESIZE                ( REG_BASE + 0x1020)
#define VI2_V_STORESIZE                ( REG_BASE + 0x2020)
#define VI3_V_STORESIZE                ( REG_BASE + 0x3020)
#define VI4_V_STORESIZE                ( REG_BASE + 0x4020)
#define VI5_V_STORESIZE                ( REG_BASE + 0x5020)
#define VI6_V_STORESIZE                ( REG_BASE + 0x6020)
#define VI7_V_STORESIZE                ( REG_BASE + 0x7020)
                                       
#define VI0_LINE_OFFSET                ( REG_BASE + 0x0024)
#define VI1_LINE_OFFSET                ( REG_BASE + 0x1024)
#define VI2_LINE_OFFSET                ( REG_BASE + 0x2024)
#define VI3_LINE_OFFSET                ( REG_BASE + 0x3024)
#define VI4_LINE_OFFSET                ( REG_BASE + 0x4024)
#define VI5_LINE_OFFSET                ( REG_BASE + 0x5024)
#define VI6_LINE_OFFSET                ( REG_BASE + 0x6024)
#define VI7_LINE_OFFSET                ( REG_BASE + 0x7024)

#define VI0_YBASE_ADDR                 ( REG_BASE + 0x0028)
#define VI1_YBASE_ADDR                 ( REG_BASE + 0x1028)
#define VI2_YBASE_ADDR                 ( REG_BASE + 0x2028)
#define VI3_YBASE_ADDR                 ( REG_BASE + 0x3028)
#define VI4_YBASE_ADDR                 ( REG_BASE + 0x4028)
#define VI5_YBASE_ADDR                 ( REG_BASE + 0x5028)
#define VI6_YBASE_ADDR                 ( REG_BASE + 0x6028)
#define VI7_YBASE_ADDR                 ( REG_BASE + 0x7028)
                                       
#define VI0_UBASE_ADDR                 ( REG_BASE + 0x002C)
#define VI1_UBASE_ADDR                 ( REG_BASE + 0x102C)
#define VI2_UBASE_ADDR                 ( REG_BASE + 0x202C)
#define VI3_UBASE_ADDR                 ( REG_BASE + 0x302C)
#define VI4_UBASE_ADDR                 ( REG_BASE + 0x402C)
#define VI5_UBASE_ADDR                 ( REG_BASE + 0x502C)
#define VI6_UBASE_ADDR                 ( REG_BASE + 0x602C)
#define VI7_UBASE_ADDR                 ( REG_BASE + 0x702C)
                                       
#define VI0_VBASE_ADDR                 ( REG_BASE + 0x0030)
#define VI1_VBASE_ADDR                 ( REG_BASE + 0x1030)
#define VI2_VBASE_ADDR                 ( REG_BASE + 0x2030)
#define VI3_VBASE_ADDR                 ( REG_BASE + 0x3030)
#define VI4_VBASE_ADDR                 ( REG_BASE + 0x4030)
#define VI5_VBASE_ADDR                 ( REG_BASE + 0x5030)
#define VI6_VBASE_ADDR                 ( REG_BASE + 0x6030)
#define VI7_VBASE_ADDR                 ( REG_BASE + 0x7030)
                                       
#define VI_INT_DLY_CNT                 ( REG_BASE + 0x0034)
                         
#define VI0_INT_EN                     ( REG_BASE + 0x0038)            
#define VI1_INT_EN                     ( REG_BASE + 0x1038)            
#define VI2_INT_EN                     ( REG_BASE + 0x2038)            
#define VI3_INT_EN                     ( REG_BASE + 0x3038)            
#define VI4_INT_EN                     ( REG_BASE + 0x4038)            
#define VI5_INT_EN                     ( REG_BASE + 0x5038)            
#define VI6_INT_EN                     ( REG_BASE + 0x6038)            
#define VI7_INT_EN                     ( REG_BASE + 0x7038)            
                                       
#define VI0_INT_STATUS                 ( REG_BASE + 0x003C)        
#define VI1_INT_STATUS                 ( REG_BASE + 0x103C)        
#define VI2_INT_STATUS                 ( REG_BASE + 0x203C)        
#define VI3_INT_STATUS                 ( REG_BASE + 0x303C)        
#define VI4_INT_STATUS                 ( REG_BASE + 0x403C)        
#define VI5_INT_STATUS                 ( REG_BASE + 0x503C)        
#define VI6_INT_STATUS                 ( REG_BASE + 0x603C)        
#define VI7_INT_STATUS                 ( REG_BASE + 0x703C)        
                                       
#define VI0_RAW_INT                    ( REG_BASE + 0x0040)
#define VI1_RAW_INT                    ( REG_BASE + 0x1040)           
#define VI2_RAW_INT                    ( REG_BASE + 0x2040)           
#define VI3_RAW_INT                    ( REG_BASE + 0x3040)           
#define VI4_RAW_INT                    ( REG_BASE + 0x4040)           
#define VI5_RAW_INT                    ( REG_BASE + 0x5040)           
#define VI6_RAW_INT                    ( REG_BASE + 0x6040)           
#define VI7_RAW_INT                    ( REG_BASE + 0x7040)
                                       
#define VI_INT_INDICATOR               ( REG_BASE + 0x0044)
#define VI_RAW_INT_INDICATOR           ( REG_BASE + 0x0048)

#define VI0_STATUS                     ( REG_BASE + 0x004C)            
#define VI1_STATUS                     ( REG_BASE + 0x104C)            
#define VI2_STATUS                     ( REG_BASE + 0x204C)            
#define VI3_STATUS                     ( REG_BASE + 0x304C)            
#define VI4_STATUS                     ( REG_BASE + 0x404C)            
#define VI5_STATUS                     ( REG_BASE + 0x504C)            
#define VI6_STATUS                     ( REG_BASE + 0x604C)            
#define VI7_STATUS                     ( REG_BASE + 0x704C)
                                       
#define VI0_BLOCK0_START               ( REG_BASE + 0x005C)            
#define VI1_BLOCK0_START               ( REG_BASE + 0x105C)            
#define VI2_BLOCK0_START               ( REG_BASE + 0x205C)            
#define VI3_BLOCK0_START               ( REG_BASE + 0x305C)            
#define VI4_BLOCK0_START               ( REG_BASE + 0x405C)            
#define VI5_BLOCK0_START               ( REG_BASE + 0x505C)            
#define VI6_BLOCK0_START               ( REG_BASE + 0x605C)            
#define VI7_BLOCK0_START               ( REG_BASE + 0x705C)  
                                       
#define VI0_BLOCK1_START               ( REG_BASE + 0x0060)            
#define VI1_BLOCK1_START               ( REG_BASE + 0x1060)            
#define VI2_BLOCK1_START               ( REG_BASE + 0x2060)            
#define VI3_BLOCK1_START               ( REG_BASE + 0x3060)            
#define VI4_BLOCK1_START               ( REG_BASE + 0x4060)            
#define VI5_BLOCK1_START               ( REG_BASE + 0x5060)            
#define VI6_BLOCK1_START               ( REG_BASE + 0x6060)            
#define VI7_BLOCK1_START               ( REG_BASE + 0x7060)
                                       
#define VI0_BLOCK2_START               ( REG_BASE + 0x0064)            
#define VI1_BLOCK2_START               ( REG_BASE + 0x1064)            
#define VI2_BLOCK2_START               ( REG_BASE + 0x2064)            
#define VI3_BLOCK2_START               ( REG_BASE + 0x3064)            
#define VI4_BLOCK2_START               ( REG_BASE + 0x4064)            
#define VI5_BLOCK2_START               ( REG_BASE + 0x5064)            
#define VI6_BLOCK2_START               ( REG_BASE + 0x6064)            
#define VI7_BLOCK2_START               ( REG_BASE + 0x7064)
                                       
#define VI0_BLOCK3_START               ( REG_BASE + 0x0068)            
#define VI1_BLOCK3_START               ( REG_BASE + 0x1068)            
#define VI2_BLOCK3_START               ( REG_BASE + 0x2068)            
#define VI3_BLOCK3_START               ( REG_BASE + 0x3068)            
#define VI4_BLOCK3_START               ( REG_BASE + 0x4068)            
#define VI5_BLOCK3_START               ( REG_BASE + 0x5068)            
#define VI6_BLOCK3_START               ( REG_BASE + 0x6068)            
#define VI7_BLOCK3_START               ( REG_BASE + 0x7068)
                                       
#define VI0_BLOCK0_SIZE                ( REG_BASE + 0x006C)            
#define VI1_BLOCK0_SIZE                ( REG_BASE + 0x106C)            
#define VI2_BLOCK0_SIZE                ( REG_BASE + 0x206C)            
#define VI3_BLOCK0_SIZE                ( REG_BASE + 0x306C)            
#define VI4_BLOCK0_SIZE                ( REG_BASE + 0x406C)            
#define VI5_BLOCK0_SIZE                ( REG_BASE + 0x506C)            
#define VI6_BLOCK0_SIZE                ( REG_BASE + 0x606C)            
#define VI7_BLOCK0_SIZE                ( REG_BASE + 0x706C)
                                       
#define VI0_BLOCK1_SIZE                ( REG_BASE + 0x0070)            
#define VI1_BLOCK1_SIZE                ( REG_BASE + 0x1070)            
#define VI2_BLOCK1_SIZE                ( REG_BASE + 0x2070)            
#define VI3_BLOCK1_SIZE                ( REG_BASE + 0x3070)            
#define VI4_BLOCK1_SIZE                ( REG_BASE + 0x4070)            
#define VI5_BLOCK1_SIZE                ( REG_BASE + 0x5070)            
#define VI6_BLOCK1_SIZE                ( REG_BASE + 0x6070)            
#define VI7_BLOCK1_SIZE                ( REG_BASE + 0x7070)
                                       
#define VI0_BLOCK2_SIZE                ( REG_BASE + 0x0074)            
#define VI1_BLOCK2_SIZE                ( REG_BASE + 0x1074)            
#define VI2_BLOCK2_SIZE                ( REG_BASE + 0x2074)            
#define VI3_BLOCK2_SIZE                ( REG_BASE + 0x3074)            
#define VI4_BLOCK2_SIZE                ( REG_BASE + 0x4074)            
#define VI5_BLOCK2_SIZE                ( REG_BASE + 0x5074)            
#define VI6_BLOCK2_SIZE                ( REG_BASE + 0x6074)            
#define VI7_BLOCK2_SIZE                ( REG_BASE + 0x7074)
                                       
#define VI0_BLOCK3_SIZE                ( REG_BASE + 0x0078)            
#define VI1_BLOCK3_SIZE                ( REG_BASE + 0x1078)            
#define VI2_BLOCK3_SIZE                ( REG_BASE + 0x2078)            
#define VI3_BLOCK3_SIZE                ( REG_BASE + 0x3078)            
#define VI4_BLOCK3_SIZE                ( REG_BASE + 0x4078)            
#define VI5_BLOCK3_SIZE                ( REG_BASE + 0x5078)            
#define VI6_BLOCK3_SIZE                ( REG_BASE + 0x6078)            
#define VI7_BLOCK3_SIZE                ( REG_BASE + 0x7078)
                                       
#define VI0_BLOCK0_COLOR               ( REG_BASE + 0x007C)            
#define VI1_BLOCK0_COLOR               ( REG_BASE + 0x107C)            
#define VI2_BLOCK0_COLOR               ( REG_BASE + 0x207C)            
#define VI3_BLOCK0_COLOR               ( REG_BASE + 0x307C)            
#define VI4_BLOCK0_COLOR               ( REG_BASE + 0x407C)            
#define VI5_BLOCK0_COLOR               ( REG_BASE + 0x507C)            
#define VI6_BLOCK0_COLOR               ( REG_BASE + 0x607C)            
#define VI7_BLOCK0_COLOR               ( REG_BASE + 0x707C)
                                       
#define VI0_BLOCK1_COLOR               ( REG_BASE + 0x0080)            
#define VI1_BLOCK1_COLOR               ( REG_BASE + 0x1080)            
#define VI2_BLOCK1_COLOR               ( REG_BASE + 0x2080)            
#define VI3_BLOCK1_COLOR               ( REG_BASE + 0x3080)            
#define VI4_BLOCK1_COLOR               ( REG_BASE + 0x4080)            
#define VI5_BLOCK1_COLOR               ( REG_BASE + 0x5080)            
#define VI6_BLOCK1_COLOR               ( REG_BASE + 0x6080)            
#define VI7_BLOCK1_COLOR               ( REG_BASE + 0x7080)
                                       
#define VI0_BLOCK2_COLOR               ( REG_BASE + 0x0084)            
#define VI1_BLOCK2_COLOR               ( REG_BASE + 0x1084)            
#define VI2_BLOCK2_COLOR               ( REG_BASE + 0x2084)            
#define VI3_BLOCK2_COLOR               ( REG_BASE + 0x3084)            
#define VI4_BLOCK2_COLOR               ( REG_BASE + 0x4084)            
#define VI5_BLOCK2_COLOR               ( REG_BASE + 0x5084)            
#define VI6_BLOCK2_COLOR               ( REG_BASE + 0x6084)            
#define VI7_BLOCK2_COLOR               ( REG_BASE + 0x7084)
                                       
#define VI0_BLOCK3_COLOR               ( REG_BASE + 0x0088)            
#define VI1_BLOCK3_COLOR               ( REG_BASE + 0x1088)            
#define VI2_BLOCK3_COLOR               ( REG_BASE + 0x2088)            
#define VI3_BLOCK3_COLOR               ( REG_BASE + 0x3088)            
#define VI4_BLOCK3_COLOR               ( REG_BASE + 0x4088)            
#define VI5_BLOCK3_COLOR               ( REG_BASE + 0x5088)            
#define VI6_BLOCK3_COLOR               ( REG_BASE + 0x6088)            
#define VI7_BLOCK3_COLOR               ( REG_BASE + 0x7088)
                                       
#define VI0_ANC0_START                 ( REG_BASE + 0x009C)            
#define VI1_ANC0_START                 ( REG_BASE + 0x109C)            
#define VI2_ANC0_START                 ( REG_BASE + 0x209C)            
#define VI3_ANC0_START                 ( REG_BASE + 0x309C)            
#define VI4_ANC0_START                 ( REG_BASE + 0x409C)            
#define VI5_ANC0_START                 ( REG_BASE + 0x509C)            
#define VI6_ANC0_START                 ( REG_BASE + 0x609C)            
#define VI7_ANC0_START                 ( REG_BASE + 0x709C)
                                       
#define VI0_ANC0_SIZE                  ( REG_BASE + 0x00A0)            
#define VI1_ANC0_SIZE                  ( REG_BASE + 0x10A0)            
#define VI2_ANC0_SIZE                  ( REG_BASE + 0x20A0)            
#define VI3_ANC0_SIZE                  ( REG_BASE + 0x30A0)            
#define VI4_ANC0_SIZE                  ( REG_BASE + 0x40A0)            
#define VI5_ANC0_SIZE                  ( REG_BASE + 0x50A0)            
#define VI6_ANC0_SIZE                  ( REG_BASE + 0x60A0)            
#define VI7_ANC0_SIZE                  ( REG_BASE + 0x70A0)
                                       
#define VI0_ANC1_START                 ( REG_BASE + 0x00A4)            
#define VI1_ANC1_START                 ( REG_BASE + 0x10A4)            
#define VI2_ANC1_START                 ( REG_BASE + 0x20A4)            
#define VI3_ANC1_START                 ( REG_BASE + 0x30A4)            
#define VI4_ANC1_START                 ( REG_BASE + 0x40A4)            
#define VI5_ANC1_START                 ( REG_BASE + 0x50A4)            
#define VI6_ANC1_START                 ( REG_BASE + 0x60A4)            
#define VI7_ANC1_START                 ( REG_BASE + 0x70A4)
                                       
#define VI0_ANC1_SIZE                  ( REG_BASE + 0x00A8)            
#define VI1_ANC1_SIZE                  ( REG_BASE + 0x10A8)            
#define VI2_ANC1_SIZE                  ( REG_BASE + 0x20A8)            
#define VI3_ANC1_SIZE                  ( REG_BASE + 0x30A8)            
#define VI4_ANC1_SIZE                  ( REG_BASE + 0x40A8)            
#define VI5_ANC1_SIZE                  ( REG_BASE + 0x50A8)            
#define VI6_ANC1_SIZE                  ( REG_BASE + 0x60A8)            
#define VI7_ANC1_SIZE                  ( REG_BASE + 0x70A8)
                                       
#define VI0_ANC0_WORD                  ( REG_BASE + 0x00AC)            
#define VI1_ANC0_WORD                  ( REG_BASE + 0x10AC)            
#define VI2_ANC0_WORD                  ( REG_BASE + 0x20AC)            
#define VI3_ANC0_WORD                  ( REG_BASE + 0x30AC)            
#define VI4_ANC0_WORD                  ( REG_BASE + 0x40AC)            
#define VI5_ANC0_WORD                  ( REG_BASE + 0x50AC)            
#define VI6_ANC0_WORD                  ( REG_BASE + 0x60AC)            
#define VI7_ANC0_WORD                  ( REG_BASE + 0x70AC)
                                       
#define VI0_ANC1_WORD                  ( REG_BASE + 0x00CC)            
#define VI1_ANC1_WORD                  ( REG_BASE + 0x10CC)            
#define VI2_ANC1_WORD                  ( REG_BASE + 0x20CC)            
#define VI3_ANC1_WORD                  ( REG_BASE + 0x30CC)            
#define VI4_ANC1_WORD                  ( REG_BASE + 0x40CC)            
#define VI5_ANC1_WORD                  ( REG_BASE + 0x50CC)            
#define VI6_ANC1_WORD                  ( REG_BASE + 0x60CC)            
#define VI7_ANC1_WORD                  ( REG_BASE + 0x70CC)

#define VI_P0_VSYNC1                   ( REG_BASE + 0x00EC)          
#define VI_P2_VSYNC1                   ( REG_BASE + 0x80EC)          
#define VI_P0_VSYNC2                   ( REG_BASE + 0x00F0)          
#define VI_P2_VSYNC2                   ( REG_BASE + 0x80F0)          
                                       
#define VI_P0_HSYNC                    ( REG_BASE + 0x00F4)           
#define VI_P2_HSYNC                    ( REG_BASE + 0x80F4)           
                                       
#define VI_PRIO0_CFG                   ( REG_BASE + 0x00F8)
#define VI_PRIO1_CFG                   ( REG_BASE + 0x10F8)
#define VI_PRIO2_CFG                   ( REG_BASE + 0x20F8)
#define VI_PRIO3_CFG                   ( REG_BASE + 0x30F8)
                                       
#define VI0_LUM_COEF0                  ( REG_BASE + 0x00FC)            
#define VI1_LUM_COEF0                  ( REG_BASE + 0x10FC)            
#define VI2_LUM_COEF0                  ( REG_BASE + 0x20FC)            
#define VI3_LUM_COEF0                  ( REG_BASE + 0x30FC)            
#define VI4_LUM_COEF0                  ( REG_BASE + 0x40FC)            
#define VI5_LUM_COEF0                  ( REG_BASE + 0x50FC)            
#define VI6_LUM_COEF0                  ( REG_BASE + 0x60FC)            
#define VI7_LUM_COEF0                  ( REG_BASE + 0x70FC)
                                       
#define VI0_LUM_COEF1                  ( REG_BASE + 0x0100)            
#define VI1_LUM_COEF1                  ( REG_BASE + 0x1100)            
#define VI2_LUM_COEF1                  ( REG_BASE + 0x2100)            
#define VI3_LUM_COEF1                  ( REG_BASE + 0x3100)            
#define VI4_LUM_COEF1                  ( REG_BASE + 0x4100)            
#define VI5_LUM_COEF1                  ( REG_BASE + 0x5100)            
#define VI6_LUM_COEF1                  ( REG_BASE + 0x6100)            
#define VI7_LUM_COEF1                  ( REG_BASE + 0x7100)
                                       
#define VI0_LUM_COEF2                  ( REG_BASE + 0x0104)            
#define VI1_LUM_COEF2                  ( REG_BASE + 0x1104)            
#define VI2_LUM_COEF2                  ( REG_BASE + 0x2104)            
#define VI3_LUM_COEF2                  ( REG_BASE + 0x3104)            
#define VI4_LUM_COEF2                  ( REG_BASE + 0x4104)            
#define VI5_LUM_COEF2                  ( REG_BASE + 0x5104)            
#define VI6_LUM_COEF2                  ( REG_BASE + 0x6104)            
#define VI7_LUM_COEF2                  ( REG_BASE + 0x7104)
                                       
#define VI0_LUM_COEF3                  ( REG_BASE + 0x0108)            
#define VI1_LUM_COEF3                  ( REG_BASE + 0x1108)            
#define VI2_LUM_COEF3                  ( REG_BASE + 0x2108)            
#define VI3_LUM_COEF3                  ( REG_BASE + 0x3108)            
#define VI4_LUM_COEF3                  ( REG_BASE + 0x4108)            
#define VI5_LUM_COEF3                  ( REG_BASE + 0x5108)            
#define VI6_LUM_COEF3                  ( REG_BASE + 0x6108)            
#define VI7_LUM_COEF3                  ( REG_BASE + 0x7108)
                                       
#define VI0_CHROMA_COEF0               ( REG_BASE + 0x010C)            
#define VI1_CHROMA_COEF0               ( REG_BASE + 0x110C)            
#define VI2_CHROMA_COEF0               ( REG_BASE + 0x210C)            
#define VI3_CHROMA_COEF0               ( REG_BASE + 0x310C)            
#define VI4_CHROMA_COEF0               ( REG_BASE + 0x410C)            
#define VI5_CHROMA_COEF0               ( REG_BASE + 0x510C)            
#define VI6_CHROMA_COEF0               ( REG_BASE + 0x610C)            
#define VI7_CHROMA_COEF0               ( REG_BASE + 0x710C)
                                       
#define VI0_CHROMA_COEF1               ( REG_BASE + 0x0110)            
#define VI1_CHROMA_COEF1               ( REG_BASE + 0x1110)            
#define VI2_CHROMA_COEF1               ( REG_BASE + 0x2110)            
#define VI3_CHROMA_COEF1               ( REG_BASE + 0x3110)            
#define VI4_CHROMA_COEF1               ( REG_BASE + 0x4110)            
#define VI5_CHROMA_COEF1               ( REG_BASE + 0x5110)            
#define VI6_CHROMA_COEF1               ( REG_BASE + 0x6110)            
#define VI7_CHROMA_COEF1               ( REG_BASE + 0x7110)
                                       
#define CH0_DESYNC_STATUS0             ( REG_BASE + 0x0114)            
#define CH1_DESYNC_STATUS0             ( REG_BASE + 0x1114)            
#define CH2_DESYNC_STATUS0             ( REG_BASE + 0x2114)            
#define CH3_DESYNC_STATUS0             ( REG_BASE + 0x3114)            
#define CH4_DESYNC_STATUS0             ( REG_BASE + 0x4114)            
#define CH5_DESYNC_STATUS0             ( REG_BASE + 0x5114)            
#define CH6_DESYNC_STATUS0             ( REG_BASE + 0x6114)            
#define CH7_DESYNC_STATUS0             ( REG_BASE + 0x7114)            
                                       
#define CH0_DESYNC_STATUS1             ( REG_BASE + 0x0118)            
#define CH1_DESYNC_STATUS1             ( REG_BASE + 0x1118)            
#define CH2_DESYNC_STATUS1             ( REG_BASE + 0x2118)            
#define CH3_DESYNC_STATUS1             ( REG_BASE + 0x3118)            
#define CH4_DESYNC_STATUS1             ( REG_BASE + 0x4118)            
#define CH5_DESYNC_STATUS1             ( REG_BASE + 0x5118)            
#define CH6_DESYNC_STATUS1             ( REG_BASE + 0x6118)            
#define CH7_DESYNC_STATUS1             ( REG_BASE + 0x7118)

#define CH0_0_FIFO_DEPTH               ( REG_BASE + 0x0200)
#define CH0_1_FIFO_DEPTH               ( REG_BASE + 0x0204)
#define CH0_2_FIFO_DEPTH               ( REG_BASE + 0x0208)
                                       
#define CH1_0_FIFO_DEPTH               ( REG_BASE + 0x1200)
#define CH1_1_FIFO_DEPTH               ( REG_BASE + 0x1204)
#define CH1_2_FIFO_DEPTH               ( REG_BASE + 0x1208)

#define CH2_0_FIFO_DEPTH               ( REG_BASE + 0x2200)
#define CH2_1_FIFO_DEPTH               ( REG_BASE + 0x2204)
#define CH2_2_FIFO_DEPTH               ( REG_BASE + 0x2208)

#define CH3_0_FIFO_DEPTH               ( REG_BASE + 0x3200)
#define CH3_1_FIFO_DEPTH               ( REG_BASE + 0x3204)
#define CH3_2_FIFO_DEPTH               ( REG_BASE + 0x3208)

#define CH4_0_FIFO_DEPTH               ( REG_BASE + 0x4200)
#define CH4_1_FIFO_DEPTH               ( REG_BASE + 0x4204)
#define CH4_2_FIFO_DEPTH               ( REG_BASE + 0x4208)

#define CH5_0_FIFO_DEPTH               ( REG_BASE + 0x5200)
#define CH5_1_FIFO_DEPTH               ( REG_BASE + 0x5204)
#define CH5_2_FIFO_DEPTH               ( REG_BASE + 0x5208)

#define CH6_0_FIFO_DEPTH               ( REG_BASE + 0x6200)
#define CH6_1_FIFO_DEPTH               ( REG_BASE + 0x6204)
#define CH6_2_FIFO_DEPTH               ( REG_BASE + 0x6208)

#define CH7_0_FIFO_DEPTH               ( REG_BASE + 0x7200)
#define CH7_1_FIFO_DEPTH               ( REG_BASE + 0x7204)
#define CH7_2_FIFO_DEPTH               ( REG_BASE + 0x7208)

#define CH0_0_FIFO_STATUS              ( REG_BASE + 0x020C)
#define CH0_1_FIFO_STATUS              ( REG_BASE + 0x0210)
#define CH0_2_FIFO_STATUS              ( REG_BASE + 0x0214)

#define CH1_0_FIFO_STATUS              ( REG_BASE + 0x120C)
#define CH1_1_FIFO_STATUS              ( REG_BASE + 0x1210)
#define CH1_2_FIFO_STATUS              ( REG_BASE + 0x1214)

#define CH2_0_FIFO_STATUS              ( REG_BASE + 0x220C)
#define CH2_1_FIFO_STATUS              ( REG_BASE + 0x2210)
#define CH2_2_FIFO_STATUS              ( REG_BASE + 0x2214)

#define CH3_0_FIFO_STATUS              ( REG_BASE + 0x320C)
#define CH3_1_FIFO_STATUS              ( REG_BASE + 0x3210)
#define CH3_2_FIFO_STATUS              ( REG_BASE + 0x3214)

#define CH4_0_FIFO_STATUS              ( REG_BASE + 0x420C)
#define CH4_1_FIFO_STATUS              ( REG_BASE + 0x4210)
#define CH4_2_FIFO_STATUS              ( REG_BASE + 0x4214)

#define CH5_0_FIFO_STATUS              ( REG_BASE + 0x520C)
#define CH5_1_FIFO_STATUS              ( REG_BASE + 0x5210)
#define CH5_2_FIFO_STATUS              ( REG_BASE + 0x5214)

#define CH6_0_FIFO_STATUS              ( REG_BASE + 0x620C)
#define CH6_1_FIFO_STATUS              ( REG_BASE + 0x6210)
#define CH6_2_FIFO_STATUS              ( REG_BASE + 0x6214)

#define CH7_0_FIFO_STATUS              ( REG_BASE + 0x720C)
#define CH7_1_FIFO_STATUS              ( REG_BASE + 0x7210)
#define CH7_2_FIFO_STATUS              ( REG_BASE + 0x7214)

#define CH0_0_STORE_STATUS             ( REG_BASE + 0x0218)
#define CH0_1_STORE_STATUS             ( REG_BASE + 0x021C)
#define CH0_2_STORE_STATUS             ( REG_BASE + 0x0220)

#define CH1_0_STORE_STATUS             ( REG_BASE + 0x1218)
#define CH1_1_STORE_STATUS             ( REG_BASE + 0x121C)
#define CH1_2_STORE_STATUS             ( REG_BASE + 0x1220)

#define CH2_0_STORE_STATUS             ( REG_BASE + 0x2218)
#define CH2_1_STORE_STATUS             ( REG_BASE + 0x221C)
#define CH2_2_STORE_STATUS             ( REG_BASE + 0x2220)

#define CH3_0_STORE_STATUS             ( REG_BASE + 0x3218)
#define CH3_1_STORE_STATUS             ( REG_BASE + 0x321C)
#define CH3_2_STORE_STATUS             ( REG_BASE + 0x3220)

#define CH4_0_STORE_STATUS             ( REG_BASE + 0x4218)
#define CH4_1_STORE_STATUS             ( REG_BASE + 0x421C)
#define CH4_2_STORE_STATUS             ( REG_BASE + 0x4220)

#define CH5_0_STORE_STATUS             ( REG_BASE + 0x5218)
#define CH5_1_STORE_STATUS             ( REG_BASE + 0x521C)
#define CH5_2_STORE_STATUS             ( REG_BASE + 0x5220)

#define CH6_0_STORE_STATUS             ( REG_BASE + 0x6218)
#define CH6_1_STORE_STATUS             ( REG_BASE + 0x621C)
#define CH6_2_STORE_STATUS             ( REG_BASE + 0x6220)

#define CH7_0_STORE_STATUS             ( REG_BASE + 0x7218)
#define CH7_1_STORE_STATUS             ( REG_BASE + 0x721C)
#define CH7_2_STORE_STATUS             ( REG_BASE + 0x7220)

#define PORT_CLK_SEL_DIV               ( REG_BASE + 0x0300)
#define PORT_RESET_CTRL                ( REG_BASE + 0x0304)

#define SUSPEND_REQ               ( REG_BASE + 0x0308)
#define SUSPEND_ACK                ( REG_BASE + 0x030C)
#endif
